### ISSUE TITLE
Move Streamlit app to openpolicedata organization

### ISSUE THREAD

**Issue by sowdm** [potto216/streamlit_ex#1]
Fork this repo under: https://github.com/openpolicedata

**Comment by potto216** [comment]
@sowdm do you want to fork it? My plan is to delete this repo once it is moved over.

**Comment by sowdm** [comment]
> @sowdm I think it would be better to create a new repo in the OPD area and not fork this. Since it will be an explorer app we should not have the other pages in the repo. I recommend creating an OPD Explorer repo with the README, requriements.txt and opd_download_singleselect_no_multiyear.py renamed something like opd_download_page.py. My plan is to delete this repo once it is moved over, however I will keep a local copy in archive.

@potto216 Completed all of the above: https://github.com/openpolicedata/OPD_Explorer
