### ISSUE TITLE
Add Streamlit badge to GitHub repo after moving to openpolicedata

### ISSUE THREAD

**Issue by sowdm** [potto216/streamlit_ex#3]
https://docs.streamlit.io/streamlit-community-cloud/get-started/share-your-app (Search for badge)

Add to both openpolicedata and streamlit app repos

**Comment by potto216** [comment]
Good idea. We should create the issue when it has been transferred over to the OPD area

**Comment by sowdm** [comment]
Moved to OPD_Explorer: https://github.com/openpolicedata/OPD_Explorer/issues/1
